### ISSUE TITLE
Dec 1st 2020 - Currency Ref Data Meeting Minutes

### ISSUE THREAD

**Issue by apapaioannou92** [finos/secref-data#45]
# Currency Reference Data Meeting
## Date
Dec 1st 2020 - 10am EST / 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Agenda
- [x] Convene & roll call (5mins)
- [x] Introduce new joiners & volunteers
- [x] Approve [Nov 17th](https://github.com/finos/secref-data/issues/43) meeting minutes - _meeting minutes were approved_
- [ ] Continue Project Plan Stage 2 – Design (Part 1: Model):
      Tasks: (expected completion by end of Nov)
     - [ ] Milestone – to agree on the model and submit it for build -Pending
     - [ ] Timeline – October 2020 to end of November 2020 (4 sessions) -Reminder
- [ ] Review ISO [Currency codes](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1670774789/Currency+-+Defining+standard+Object) and [sample data](https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/1864138753/Sample+data).
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [x] Aitana to connect Vijay and the group with the ISO group
- [x] Aitana to check with ISO the subscription requirements
- [x] Vijay Chandel to check internally how to make publicly available the model he designed in Legend Studio in June, and to set up a meeting with Sailesh to review the features
- [x] Alex to follow up with Ted about:
    - [x] a) Updating the Excel file with the draft description for the columns of the Curr Ref DB based on today's discussion
    - [x] b) Ted Sanborn to confirm if official non-deliverable currency list exists within ISDA 

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=mf27815a7807f13f1d0974a973196cb4c)
- Meeting Number: 127 819 0322
- Join by phone: +1.415.655.0003 USA Toll | +44-20319-88141 UK Toll | Access code: 127 819 0322
- Password: VXcd2eQgh82
- [Global call-in numbers](https://finos.webex.com/finos/globalcallin.php?serviceType=MC&ED=582460637&tollFree=0)

**Comment by saileshpandey** [comment]
Hi

**Comment by aitana16** [comment]
hi

**Comment by TLATER** [comment]
o/

**Comment by toshaellison** [comment]
present

**Comment by ElaineFraser** [comment]
hi

**Comment by RichardWagener365** [comment]
Hi

**Comment by apapaioannou92** [comment]
hi

**Comment by Vijayesh-Chandel** [comment]
Hi All - regarding the model, you should now be able to view it in Studio as it has been successfully merged. Once you enter into the CurrencyRefData project and create your workspace, you should see the folder/package called 'Model' which contains all our modelling to date.

@TSanborn-ISDA - regarding the draft descriptions, instead of uploading an excel file you should be able to directly update them in our Studio model for each property/class and submit a review. We can then merge them post which the WG will be able to view them directly.

Let us know if any issues!

**Comment by TSanborn-ISDA** [comment]
Hi Vijay,
Thanks for the update.  I will aim to make that addition next week.
Best Regards,
Ted Sanborn
ISDA

**Comment by TSanborn-ISDA** [comment]
Hi Vijay,
I have added the descriptions and made a few related changes, then attempted to contribute, but encountered a large number of compilation errors.  I was able to resolve many of them, but was stumped by the one shown below:

[cid:image001.png@01D6D2BD.DCC1D230]

Please advise on how to resolve.

There may be more after this one.  It seems as if the editor only displays one error at a time, so that the user is unable to see the other errors until the current one is resolved.

Best Regards,
Ted

From: Ted Sanborn
Sent: Friday, December 11, 2020 8:45 AM
To: finos/secref-data <reply@reply.github.com>; finos/secref-data <secref-data@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [finos/secref-data] Dec 1st 2020 - Currency Ref Data Meeting Minutes (#45)

Hi Vijay,
Thanks for the update.  I will aim to make that addition next week.
Best Regards,
Ted Sanborn
ISDA

**Comment by Vijayesh-Chandel** [comment]
@TSanborn-ISDA: I'm unable to view the screenshot - are you able to attach it here? Checking are you working off the latest version of the model too as we have made a few tweaks so may need to update your workspace which could resolve the errors you see

**Comment by TSanborn-ISDA** [comment]
Hi Vijay,
I had downloaded the latest version of the model.  The error message is copied below and attached.
Ted

[cid:image001.png@01D6D2C2.45734940]
